import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f0f0f",
    alignItems: "stretch",
    marginLeft: -10,
    marginRight: -10,
    paddingHorizontal: 10,
    paddingBottom: 80,
  },
  titulo:{
    color: "#fff",
    marginLeft:10,
    fontSize: 19,
    fontWeight: "600",
  },
  addValor:{
    flexDirection: "row",
    backgroundColor: "#1c1c1c",
    padding:12,
    margin: 20,
    borderRadius: 35,
    alignItems: "center",
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#242424'
  },

  InputValor:{
    color: "#55ff00",
    marginLeft: "15%",
    borderRadius: 12,
    width: "40%",
    backgroundColor: "#1c1c1c",
    height: 52,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  valorWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
    marginLeft: 12,
  },
  currency: {
    color: '#55ff00',
    fontWeight: '700',
    marginRight: 8,
    fontSize: 18,
  },
  input: {
    width: "100%",
    height: 52,
    backgroundColor: "#1c1c1c",
    color: "#fff",
    fontSize: 16,
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 18,
  },
  inputFull: {
    paddingHorizontal: 20,
    marginBottom: 6,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#121212',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginHorizontal: 18,
    marginBottom: 10,
    borderRadius: 10,
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#1f1f1f',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  listItemText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  listItemSub: {
    color: '#9b9b9b',
    fontSize: 13,
    marginTop: 4,
  },
  saveWrapper: {
    paddingHorizontal: 18,
    marginTop: 10,
    marginBottom: 84,
  },
  saveButton: {
    backgroundColor: '#5a39ff',
    paddingVertical: 14,
    borderRadius: 30,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
})