import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f0f0f",
    alignItems: "stretch",
    marginLeft: -10,
    marginRight: -10,
    paddingHorizontal: 10,
  },
  titulo:{
    color: "#fff",
    marginLeft:10,
    fontSize: 19,
    fontWeight: "600",
  },
  addValor:{
    flexDirection: "row",
    backgroundColor: "#161616",
    padding: 12,
    margin: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: 'space-between',
  },

  InputValor:{
    color: "#55ff00",
    borderRadius: 10,
    width: "50%",
    backgroundColor: "#1b1b1b",
    height: 46,
    paddingHorizontal: 10,
    justifyContent: 'center',
    fontWeight: '600',
    fontSize: 17,
  },
  valorWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
    marginLeft: 12,
  },
  currency: {
    color: '#55ff00',
    fontWeight: '700',
    marginRight: 8,
    fontSize: 18,
  },
  input: {
    width: "100%",
    height: 46,
    backgroundColor: "#1b1b1b",
    color: "#fff",
    fontSize: 15,
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  inputFull: {
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#161616',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 10,
  },
  iconBox: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: '#1f1f1f',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  listItemText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  listItemSub: {
    color: '#9b9b9b',
    fontSize: 13,
    marginTop: 4,
  },
  saveWrapper: {
    paddingHorizontal: 16,
    marginTop: 8,
    marginBottom: 84,
  },
  saveButton: {
    backgroundColor: '#5a39ff',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15,
  },
})